baseURL = "https://cdrinmatane.github.io/blog-hugo/"
title = "CDRIN Research Blog"

theme = "anubis" 
#paginate = 8

disqusShortname = ""
googleAnalytics = ""

[author]
name = ""

[params]
author = "CDRIN"
description = "CDRIN Research Blog."
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
mathjax = false

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

#[[params.social]]
#id = "docs"
#url = "https://gohugo.io/documentation/"

[[params.social]]
id = "github"
url = "https://github.com/cdrinmatane"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "https://www.cdrin.com/"
weight = 1

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true